### ISSUE TITLE
invalid type: integer in js console

### ISSUE THREAD

**Issue by akonior** [noir-lang/tiny-noirjs-app#1]
### Aim

Run `noirjs_demo` demo app

### Expected Behavior

Success proof generate/verify

### Bug

After upgrading noir versions in `package.json`

```
"dependencies": {
  "@noir-lang/backend_barretenberg": "0.19.4",
  "@noir-lang/noir_js": "0.19.4"
},
```

and `npm install` and `npm run start`
I'm getting the following error in browser js console:
```
noirc_abi_wasm.js:245 Uncaught (in promise) Error: invalid type: integer `1`, expected struct Range at line 1 column 160
    at imports.wbg.__wbg_constructor_fc0c89256754526e (noirc_abi_wasm.js:245:21)
    at noirc_abi_wasm_bg.wasm:0xfaf6
    at abiEncode (noirc_abi_wasm.js:135:14)
    at generateWitness (witness_generation.mjs:10:24)
    at Noir.execute (program.mjs:51:31)
    at async Noir.generateFinalProof (program.mjs:67:29)
    at async HTMLDocument.<anonymous> (app.js:10:17)
```

### To Reproduce

1. Update versions to `0.19.4`
2. `npm install`, `npm run start`
3. go to browser js console

### Would you like to submit a PR for this Issue?

No

**Comment by akonior** [comment]
Recompiling circuits solves the issue:
```
cd circuit
noirup -v 0.19.4
nargo build
cd ..
npm run start
```
